### ISSUE TITLE
/mute

### ISSUE THREAD

**Issue by eskohks** [BraveHearts/Mapas-de-BraveHearts#15]
El /mute no sirve :v :v:

**Comment by RubeGamerV** [comment]
Si funciona, talvez tienes permisos insuficientes

**Comment by eskohks** [comment]
Por que diria eso sin tener op .-.
Obviamente fue cuando tenia op, muteaba gente y seguian hablando
PD: Eras usuarios normales, de otros equipos.

**Comment by RubeGamerV** [comment]
Ok, lo revisare otra vez para ver si no funciona correctamente.

**Comment by eskohks** [comment]
Oc, saludos :v: :v: :smile: :smile: :smile: :heart: :heart: :clap:
